### ISSUE TITLE
Window control buttons hidden below UI (Windows 10)

### ISSUE THREAD

**Issue by InvisCo** [ranmaru22/firefox-vertical-tabs#27] opened 2022-05-20 16:17 UTC
I updated to the latest CSS code on the repo to try and fix the problem from issue #24, but instead the window control buttons disappeared.

![image](https://user-images.githubusercontent.com/20621549/169568757-61a4c021-6c6c-48a3-864d-d084c31543e7.png)
You can see from the image that the top part of the close button is hidden under the top bar of the browser UI. This screenshot was taken after changing the _--uc-toolbar-height_ value to a large number.

I am on version 100.0.2 on Windows 10.

**Comment by ranmaru22** [comment] 2022-05-20 18:55
Interesting, this might be because of the recent z-index change I made in #26 to fix issue #22. Is seems that the window controls in Windows sit on another z-index than the ones on Linux or macOS.

I can't reproduce that because I don't own a Windows machine, but could you try setting the z-index of `.titlebar-buttonbox-container` inside the `/* Windows specific styles */` to something higher than 1000 and see if that fixes it?

If it does, I'll deploy that change.

**Comment by InvisCo** [comment] 2022-05-20 19:11
No, that did not make any difference. 

I added the following to userChrome.css, but no change in Firefox.
```
.titlebar-buttonbox-container {
    z-index: 2000;
}
```

**Comment by ranmaru22** [comment] 2022-05-20 19:15
In that case it's probably a different class that needs to be changed. I can't figure out which one without access to a Windows machine, unfortunately.

For now, you can probably fix this by removing this bit from the code, lines 135 and following:

```css
#nav-bar, #urlbar {
    z-index: 100;
}
```

This will reintroduce issue #22 but that only occurred in rare cases anyway and it probably less jarring than not having titlebar buttons.

**Comment by leandroprz** [comment] 2022-05-31 00:39
I fixed it by adding `z-index: 0;` as shown below:

```
    :root:not([inFullscreen]) #nav-bar {
        margin-top: calc(0px - var(--uc-toolbar-height));
        z-index: 0;
    }
```
Result: https://user-images.githubusercontent.com/1398896/171071647-024c30c6-ba08-40f3-b9a8-208eeeb20d4e.png

**Comment by InvisCo** [comment] 2022-05-31 03:40
> I fixed it by adding `z-index: 0;` as shown below:
> 
> ```
>     :root:not([inFullscreen]) #nav-bar {
>         margin-top: calc(0px - var(--uc-toolbar-height));
>         z-index: 0;
>     }
> ```
> 
> Result: https://user-images.githubusercontent.com/1398896/171071647-024c30c6-ba08-40f3-b9a8-208eeeb20d4e.png

Making this change and adding back the bit that I removed at line 135 made the URL suggestion box disappear. 

In the screenshot I am typing something in the address bar, but no suggestions appear.

![image](https://user-images.githubusercontent.com/20621549/171088093-5a09a253-4740-4378-8898-13c43348028f.png)

**Comment by delgadobosso** [comment] 2022-07-20 18:03
I was taking a look at this through the Inspector and it seems like the z-index wasn't working on ".titlebar-buttonbox-container" because it's not a positioned element. I added "position: absolute" to it alongside the "z-index: 2000" and it seems to be showing up properly now.

Also I'm not sure if this is just me or not, but the buttons seem to align better without the "margin-top: 7px".

**Comment by ranmaru22** [comment] 2022-07-21 16:59
Thanks, I'll take a look at the z-index later. As for the buttons, PR #36 by @onurhanak addressed this and is now merged in. So hopefully it looks better now.

**Closed** 2022-08-25 07:48 UTC
Labels: bug, help wanted
