### ISSUE TITLE
Minimize, expand & close buttons disappeared in 123.0b1

### ISSUE THREAD

**Issue by UnholySheep** [ranmaru22/firefox-vertical-tabs#155] opened 2024-01-24 08:36 UTC
I'm running Firefox Dev 123.0b1. It appears I can't minimize, expand or close with the buttons anymore, is this something on my end or a Mozilla issue?

![M8mcPJMTPf](https://github.com/ranmaru22/firefox-vertical-tabs/assets/115432589/8a418314-ca95-4e92-8421-597ef5e4ac62)

**Comment by ranmaru22** [comment] 2024-01-24 08:54
If you're on Linux, this might be related to your GTK theme and the way it handles windows decorations. 

If you're on Windows, I can't really chime in because I don't use or know anything about it, but there it might be worth checking around in the settings if there exists an option related to window decorations there too. 

I could imagine Mozilla changing something around there, yes. They've done so in the past.

**Comment by Carighan** [comment] 2024-01-24 15:42
If anyone finds a solution to this I'm all ear, just updated and I have the same issue.

**Comment by suhankins** [comment] 2024-01-26 00:01
This worked for me
```css
#titlebar {
    z-index: 3;
}
```

**Comment by suhankins** [comment] 2024-01-26 00:14
Probably a bandaid fix but works for me
```css
    .titlebar-buttonbox * {
        pointer-events: auto;
    }
    #titlebar {
        z-index: 3;
        pointer-events: none;
    }
```

**Comment by Diablo-D3** [comment] 2024-01-27 08:05
ranmaru22 is going to close this ticket as he doesn't support beta/nightly versions of Firefox.

However, because this exact issue keeps being re-reported, I suggest stickying this ticket and leaving it open until stable Firefox ships with this breakage.

**Comment by ranmaru22** [comment] 2024-01-27 09:27
The reason I don't do fixes for nightlies is that the API changes all the time. Sometimes you fix something only for the fix to break something again two days later. It's really annoying. It could just be that the issue disappears completely once this version hits the dev channel (which is the only early access channel I'm willing to support). It happened before in the past. 

Let me know if this does persist into dev or even stable, though. If it does, I'll put the fix in immediately.

**Comment by MikeAtom** [comment] 2024-01-28 17:22
same issue on firefox 122.0, also toggle button does not work

**Comment by 0x8008** [comment] 2024-02-01 14:08
Same on Windows. Can confirm 

> > Probably a bandaid fix but works for me
> > ```css
> >     .titlebar-buttonbox * {
> >         pointer-events: auto;
> >     }
> >     #titlebar {
> >         z-index: 3;
> >         pointer-events: none;
> >     }
> > ```
> 
> Thank you so much!

this fix works.

**Comment by ranmaru22** [comment] 2024-02-01 20:57
Thanks, I'll put this in and push it. Dev Channel is on 123 now, and it seems that 122 is affected as well, according to @MikeAtom. I'd say that qualifies.

I've put it into the Windows-specific styles for now since it does not seem to affect Linux or macOS. If anyone can reproduce this on those systems, let me know.

**Closed** 2024-02-01 20:57 UTC
